language: node_js
sudo: false
node_js:
    - "6"
    - "7"
    - "8"
matrix:
  fast_finish: true
  include:
    - node_js : "8"
  allow_failures:
    - node_js: "8"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
    - npm install 

script:
  - npm run test
  - npm run test:cover
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - git config --global user.email $GITHUB_USER_EMAIL
  - git config --global user.name $GITHUB_USER_NAME
  # - npm run deploy

before_deploy:
 - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build/
 target_branch: gh-pages
 email: $GITHUB_USER_EMAIL
 name: $GITHUB_USER_NAME
 on:
   branch: master
