language: node_js
sudo: false
node_js:
    - "6"
    - "7"
    - "8"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
    - npm install 

script:
  - npm run test
  - npm run test:cover
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run deploy
