language: node_js
sudo: required
dist: trusty
node_js:
    - "10"
    - "11"
    - "12"

services:
  - docker

matrix:
  fast_finish: true
  include:
    - node_js : "8"
  allow_failures:
    - node_js: "8"

cache:
  directories:
    - client/node_modules
    - server/node_modules


script:
  - cd client; npm install
  - npm run test:cover
  - cd ..
  - cd server; npm install
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - git config --global user.email $GITHUB_USER_EMAIL
  - git config --global user.name $GITHUB_USER_NAME

before_deploy:
 - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build/
 target_branch: gh-pages
 email: $GITHUB_USER_EMAIL
 name: $GITHUB_USER_NAME
 on:
   branch: master
